line-length = 120
target-version = "py312"
extend-exclude = [
    ".github",
]

[lint]
select = [
    "B", # flake8-bugbear
    "E", # pycodestyle
    "F", # pyflakes
    "FIX",
    "G",
    "I", # isort
    "PTH",
    "RUF",
    "SIM", # flake8-simplify
    "T20",
    "UP", # pyupgrade
]

[lint.isort]
case-sensitive = true

[lint.pydocstyle]
convention = "google"