# Generated by Django 5.0.4 on 2024-07-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="year_end",
            field=models.CharField(help_text="The year the series ended.", max_length=100),
        ),
        migrations.AlterField(
            model_name="series",
            name="year_start",
            field=models.CharField(help_text="The year the series started.", max_length=100),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="bio",
            field=models.TextField(help_text="The biography of the speaker.", max_length=5000),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="name",
            field=models.CharField(help_text="The name of the speaker.", max_length=200),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="series",
            field=models.ManyToManyField(
                blank=True,
                help_text="The videos related to series.",
                null=True,
                related_name="+",
                to="catalogue.series",
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="thumbnail",
            field=models.CharField(help_text="The thumbnail for the speaker.", max_length=200),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="videos",
            field=models.ManyToManyField(
                blank=True,
                help_text="The videos related to video.",
                null=True,
                related_name="+",
                to="catalogue.video",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="speaker",
            field=models.ManyToManyField(
                blank=True,
                help_text="The speakers/artist in the video.",
                null=True,
                to="catalogue.speaker",
            ),
        ),
    ]
