# Generated by Django 5.0.4 on 2025-01-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_bible_book_name_alter_topic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='id_number',
            field=models.CharField(help_text='An ID number used when importing the old database', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.TextField(help_text='Thumbnail Location', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='id',
            field=models.CharField(help_text='An ID number used for linking', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.CharField(help_text='An ID number used for linking', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.CharField(help_text='Another unique identifier used for database linking', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
