# Generated by Django 5.0.4 on 2025-01-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_series_id_number_video_thumbnail_alter_speaker_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='id_number',
        ),
    ]
