# Generated by Django 5.1 on 2025-03-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_remove_series_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='id_number',
            field=models.CharField(help_text='An ID number used when importing the old database', max_length=20, null=True),
        ),
    ]
