# Generated by Django 5.2.3 on 2025-09-26 22:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0007_alter_bible_book_name"),
        ("catalogue", "0012_alter_topic_id"),
    ]

    operations = []
