# Generated by Django 5.2.3 on 2025-09-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0013_merge_0007_alter_bible_book_name_0012_alter_topic_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="series",
            name="id_number",
        ),
        migrations.AlterField(
            model_name="topic",
            name="category",
            field=models.CharField(help_text="Enter the category of the topic", max_length=200, unique=True),
        ),
    ]
