# Generated by Django 5.2.3 on 2025-09-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0014_remove_series_id_number_alter_topic_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="category",
            field=models.CharField(help_text="Enter the category of the topic", max_length=200),
        ),
    ]
