# Generated by Django 5.2.3 on 2025-09-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0015_alter_topic_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="url",
            field=models.URLField(help_text="A link to where the video is hosted."),
        ),
    ]
