# Generated by Django 5.2.3 on 2025-09-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0016_alter_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="id_number",
            field=models.CharField(help_text="A unique video identifier generated e.g.YT1234", max_length=100),
        ),
    ]
