# Generated by Django 5.2.3 on 2025-09-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0017_alter_video_id_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="id_number",
            field=models.CharField(default=0, help_text="The id number of the series.", max_length=200),
            preserve_default=False,
        ),
    ]
