# Generated by Django 5.2.3 on 2025-09-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0018_series_id_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="id_number",
            field=models.CharField(
                help_text="A unique video identifier generated e.g.YT1234", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="url",
            field=models.URLField(help_text="A link to where the video is hosted.", unique=True),
        ),
    ]
