# Generated by Django 5.2.3 on 2025-10-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0019_alter_video_id_number_alter_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="name",
            field=models.CharField(help_text="The name of the series.", max_length=256),
        ),
    ]
