# Generated by Django 6.0.6 on 2026-06-12 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0020_alter_series_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="alternate_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Other places this video is hosted: [{'url': ..., 'platform': 'youtube'|'vimeo'|'other'}]. The legacy catalogue holds both a Vimeo and a YouTube copy for most programmes; `url` is the primary, these are the rest.",
            ),
        ),
        migrations.CreateModel(
            name="RelatedResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("transcript", "Transcript"), ("audio", "Audio"), ("other", "Other")], max_length=20
                    ),
                ),
                (
                    "url",
                    models.URLField(help_text="Resolved destination (bit.ly already unshortened).", max_length=500),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_resources",
                        to="catalogue.video",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("video", "kind", "url"), name="unique_resource_per_video")
                ],
            },
        ),
    ]
