# Generated by Django 6.0.6 on 2026-06-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0021_video_alternate_urls_relatedresource"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveStream",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("video_id", models.CharField(help_text="YouTube video id", max_length=20, unique=True)),
                ("channel_id", models.CharField(max_length=40)),
                ("channel_title", models.CharField(blank=True, default="", max_length=200)),
                ("title", models.CharField(max_length=300)),
                ("thumbnail", models.TextField(blank=True, null=True)),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("upcoming", "Upcoming"), ("live", "Live"), ("ended", "Ended")],
                        default="upcoming",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
