# Generated by Django 6.0.6 on 2026-06-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0022_livestream"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Runtime in whole seconds, harvested from the hosting platform (YouTube/Vimeo).",
                null=True,
            ),
        ),
    ]
