# Generated by Django 6.0.6 on 2026-06-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0023_video_duration_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                db_index=True,
                default="published",
                help_text="Draft videos are hidden from the public site until published.",
                max_length=12,
            ),
        ),
    ]
