# Generated by Django 6.0.6 on 2026-06-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0024_video_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When set, the video is soft-deleted: hidden everywhere but retained for restore.",
                null=True,
            ),
        ),
    ]
