# Generated by Django 6.0.6 on 2026-06-15 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0025_video_deleted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoEnrichment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("summary", models.TextField(blank=True, default="", help_text="A one- or two-sentence AI summary.")),
                ("topics", models.JSONField(blank=True, default=list, help_text="AI-suggested topic strings.")),
                (
                    "audience",
                    models.CharField(blank=True, default="", help_text="AI-suggested audience.", max_length=200),
                ),
                (
                    "bible_passages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Cross-checked Bible references: [{'book', 'label', 'chapter'?, ...}].",
                    ),
                ),
                ("keywords", models.JSONField(blank=True, default=list, help_text="AI-suggested search keywords.")),
                (
                    "model",
                    models.CharField(
                        blank=True, default="", help_text="The Ollama model that generated this.", max_length=100
                    ),
                ),
                (
                    "prompt_version",
                    models.PositiveIntegerField(default=0, help_text="enrichment.PROMPT_VERSION at generation time."),
                ),
                (
                    "generated_at",
                    models.DateTimeField(blank=True, help_text="When this enrichment was generated.", null=True),
                ),
                (
                    "video",
                    models.OneToOneField(
                        help_text="The video this enrichment describes.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment",
                        to="catalogue.video",
                    ),
                ),
            ],
        ),
    ]
