# Generated by Django 5.0.2 on 2024-02-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='series',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.series'),
        ),
    ]
