# Generated by Django 5.0.2 on 2024-02-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_speaker_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bible_book',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
