# Generated by Django 5.0.2 on 2024-02-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_video_bible_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='summary',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
