# Generated by Django 5.0.2 on 2024-03-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_series_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, max_length=100, null=True)),
                ('topic', models.ManyToManyField(to='catalog.topic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='ministry',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.ministry'),
        ),
    ]
