# Generated by Django 5.0.2 on 2024-03-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_ministry_video_ministry'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='IDnum',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='IsLivestream',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='label_episode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='label_series',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='label_subseries',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='series',
            field=models.ManyToManyField(to='catalog.series'),
        ),
        migrations.RemoveField(
            model_name='video',
            name='bible_book',
        ),
        migrations.AlterField(
            model_name='video',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='ministry',
            field=models.ManyToManyField(to='catalog.ministry'),
        ),
        migrations.AlterField(
            model_name='video',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the video', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='BibleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(max_length=50)),
                ('series', models.ManyToManyField(to='catalog.series')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, max_length=100, null=True)),
                ('Ministry', models.ManyToManyField(to='catalog.ministry')),
                ('Series', models.ManyToManyField(to='catalog.series')),
                ('topic', models.ManyToManyField(to='catalog.topic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='demographic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.demographic'),
        ),
        migrations.AddField(
            model_name='video',
            name='bible_book',
            field=models.ManyToManyField(to='catalog.biblebook'),
        ),
    ]
