"""Slowly enrich the whole catalogue with AI metadata (Epic #201, E2).

Walks every alive video that lacks a *current* enrichment and stores one via
``catalogue.enrichment.store_enrichment`` (which calls the self-hosted Ollama
model and upserts a ``VideoEnrichment`` row, folding keywords/summary/topics
invisibly into search).

Designed to run unattended as an off-peak cron (see docs/DEPLOYMENT.md):

- **Resumable + idempotent.** Only processes videos with no enrichment, or one
  generated by an older ``PROMPT_VERSION`` — so re-running continues where it
  left off, and a finished catalogue is a near-instant no-op. ``--refresh``
  re-does everything (e.g. after a prompt change without a version bump).
- **Polite to shared infra.** ``--sleep`` throttles between calls (tgoml is
  shared); ``--max-runtime`` stops gracefully inside a cron window; ``--limit``
  caps a single run.
- **Loud but non-fatal.** A model failure (unreachable/unparseable → no row
  stored) or an unexpected per-video error is logged and skipped; the run
  carries on and the video is retried next time.
- **Prints a running ETA** (done/total, rate, projected finish) so a multi-day
  background fill is observable.
"""

import time

from django.core.management.base import BaseCommand
from django.db.models import Q
from django.utils import timezone

from catalogue.enrichment import PROMPT_VERSION, store_enrichment
from catalogue.models.video import Video


def pending_videos(refresh=False):
    """Alive videos still needing enrichment: no row, or one from an older
    ``PROMPT_VERSION``. ``refresh=True`` returns every alive video (re-enrich)."""
    qs = Video.objects.all().order_by("date_created", "id")
    if refresh:
        return qs
    return qs.filter(Q(enrichment__isnull=True) | Q(enrichment__prompt_version__lt=PROMPT_VERSION))


def format_eta(done, total, elapsed_seconds):
    """A human progress/ETA line. Pure: derives rate from work done so far and
    projects the finish. Returns e.g.
    ``"42/9862 (0.4%) · 3.1s/video · ETA ~8h27m (finish 14 Jun 06:11)"``."""
    pct = (done / total * 100) if total else 100.0
    if not done or not elapsed_seconds:
        return f"{done}/{total} ({pct:.1f}%)"
    per = elapsed_seconds / done
    remaining = max(total - done, 0)
    eta_seconds = remaining * per
    finish = timezone.localtime(timezone.now() + timezone.timedelta(seconds=eta_seconds))
    return (
        f"{done}/{total} ({pct:.1f}%) · {per:.1f}s/video · "
        f"ETA ~{_human_duration(eta_seconds)} (finish {finish:%d %b %H:%M})"
    )


def _human_duration(seconds):
    seconds = int(seconds)
    days, rem = divmod(seconds, 86400)
    hours, rem = divmod(rem, 3600)
    minutes, _ = divmod(rem, 60)
    if days:
        return f"{days}d{hours}h"
    if hours:
        return f"{hours}h{minutes}m"
    return f"{minutes}m"


class Command(BaseCommand):
    help = "Store AI enrichment for videos that lack a current one (resumable, throttled)."

    def add_arguments(self, parser):
        parser.add_argument("--limit", type=int, default=None, help="Process at most N videos this run.")
        parser.add_argument(
            "--sleep", type=float, default=2.0, help="Seconds to wait between videos (polite throttle; default 2.0)."
        )
        parser.add_argument(
            "--max-runtime", type=float, default=None, help="Stop gracefully after this many seconds of wall-clock."
        )
        parser.add_argument(
            "--refresh", action="store_true", help="Re-enrich every video, ignoring existing enrichments."
        )
        parser.add_argument("--model", default=None, help="Override the Ollama model for this run.")
        parser.add_argument(
            "--progress-every", type=int, default=10, help="Print an ETA line every N videos (default 10)."
        )

    def handle(self, *args, **options):
        limit = options["limit"]
        sleep_seconds = options["sleep"]
        max_runtime = options["max_runtime"]
        refresh = options["refresh"]
        model = options["model"]
        progress_every = max(options["progress_every"], 1)

        qs = pending_videos(refresh=refresh)
        total = qs.count()
        if total == 0:
            self.stdout.write(self.style.SUCCESS("Nothing to enrich — the catalogue is up to date."))
            return

        target = min(total, limit) if limit else total
        self.stdout.write(f"Enriching {target} of {total} pending video(s) (prompt v{PROMPT_VERSION})…")

        started = time.monotonic()
        done = stored = empty = errors = 0

        # .iterator() keeps memory flat over a 10k-row walk; the throttle dwarfs
        # any query cost, so server-side cursoring is fine.
        for video in qs.iterator():
            if limit and done >= limit:
                break
            if max_runtime is not None and (time.monotonic() - started) >= max_runtime:
                self.stdout.write(self.style.WARNING(f"Reached --max-runtime ({max_runtime}s); stopping gracefully."))
                break

            try:
                result = store_enrichment(video, model=model)
            except Exception as exc:  # never let one bad row abort the batch
                errors += 1
                self.stderr.write(self.style.ERROR(f"  ! {video.pk} ({video.name!r}): {exc}"))
            else:
                if result is None:
                    # Model returned nothing (unreachable/unparseable) — left for retry.
                    empty += 1
                    self.stderr.write(self.style.WARNING(f"  · {video.pk}: model returned nothing (will retry)"))
                else:
                    stored += 1

            done += 1
            if done % progress_every == 0 or done == target:
                self.stdout.write(f"  {format_eta(done, target, time.monotonic() - started)}")

            if sleep_seconds and done != target:
                time.sleep(sleep_seconds)

        self.stdout.write(
            self.style.SUCCESS(f"Done: {stored} stored, {empty} empty/retry, {errors} errors ({done} processed).")
        )
