name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false # Don't cancel production deploys if a new commit is pushed to main

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: production
      base_path: /srv/claytontv
      gunicorn_service: gunicorn-claytontv.service
      url: https://claytontv.co.uk/
      reindex: true
    secrets: inherit
