name: Format and Commit Django Project

on:
  pull_request:

jobs:
  format-and-commit:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
          cache: 'pipenv'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install Python dependencies
        run: pipenv install

      - name: Format code with Black
        run: pipenv run black .

      # TODO: npm install and run prettier w/ tailwindcss plugin

      - name: Commit Changes (if any)
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'githubbot@claytontv.co.uk'
          git add .
          git commit -m "Apply code formatting" || exit 0
          git push