name: Github Actions
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install pipenv
      run: python3.12 -m pip install pipenv
      
    - name: Install Python dependencies
      run: pipenv install

    - name: Install Node.js dependencies
      run: npm install

    - name: Run migrations
      run: pipenv run python manage.py migrate

    - name: Run tests
      run: pipenv run pytest catalogue/tests.py
    
