name: Run tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.1'
        cache: 'pipenv'

    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

    - name: Install Python dependencies
      run: | 
        pipenv install --dev

    - name: Run migrations
      run: pipenv run python manage.py migrate

    - name: Set DJANGO_SETTINGS_MODULE environment variable
      run: echo "DJANGO_SETTINGS_MODULE=app.settings" >> $GITHUB_ENV

    - name: Run tests
      run: pipenv run pytest catalogue/tests.py
    
